//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electrichka.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public int categoryId { get; set; }
        public int directionId { get; set; }
        public int stationFromId { get; set; }
        public int stationToId { get; set; }
        public decimal cost { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Directions Directions { get; set; }
        public virtual Stations Stations { get; set; }
        public virtual Stations Stations1 { get; set; }
    }
}
